language: r
r:
  - release
  - devel
os:
  - linux
warnings_are_errors: true
sudo: false
cache: packages
env:
  global:
  - NOT_CRAN="true"
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
